-- This setup script was generated by render_sql_template.py in the aue_interlis git repo.
-- 
-- Usage:
-- This script is intended to directly run after importing the corresponding INTERLIS
-- schema and catalogues using ili2pg. It sets up common Postgres-specific functionality 
-- such:
--  - adding last_modified columns and corresponding trigger functionality
--  - setting up priviledges 
--  - adding enum constraints that ili2pg doesn't implement
--  - adding not null constraints (this is a workaround for mandatory catalogue fkey columns
--    not getting materialized with NOT NULL by ili2pg)


-- Drop unused catref tables -----------------------------------------------------------
DROP TABLE gl_ersatzbiotope.ersatzmassnahme_catref;

-- Add NOT NULL constraints ------------------------------------------------------------


-- Create Domains for custom Enum-Types ------------------------------------------------

-- Add Trigger Setup ------------------------------------------------------------

-- ersatzbiotop
ALTER TABLE gl_ersatzbiotope.ersatzbiotop
ADD COLUMN last_modified timestamp without time zone;

CREATE FUNCTION gl_ersatzbiotope.ersatzbiotop_update()
  RETURNS TRIGGER
  LANGUAGE 'plpgsql'
AS $BODY$

BEGIN

NEW.last_modified = localtimestamp(0);


RETURN NEW;
END;
$BODY$;

ALTER FUNCTION gl_ersatzbiotope.ersatzbiotop_update()
  OWNER TO gl_ersatzbiotope_write;

CREATE TRIGGER ersatzbiotop_update
  BEFORE UPDATE
  ON gl_ersatzbiotope.ersatzbiotop
  FOR EACH ROW
  EXECUTE FUNCTION gl_ersatzbiotope.ersatzbiotop_update();

-- to_flaeche
ALTER TABLE gl_ersatzbiotope.to_flaeche
ADD COLUMN last_modified timestamp without time zone;

CREATE FUNCTION gl_ersatzbiotope.to_flaeche_update()
  RETURNS TRIGGER
  LANGUAGE 'plpgsql'
AS $BODY$

BEGIN

NEW.last_modified = localtimestamp(0);
NEW.flaeche_m2 = ST_Area(geo_obj);


RETURN NEW;
END;
$BODY$;

ALTER FUNCTION gl_ersatzbiotope.to_flaeche_update()
  OWNER TO gl_ersatzbiotope_write;

CREATE TRIGGER to_flaeche_update
  BEFORE UPDATE
  ON gl_ersatzbiotope.to_flaeche
  FOR EACH ROW
  EXECUTE FUNCTION gl_ersatzbiotope.to_flaeche_update();

-- to_linie
ALTER TABLE gl_ersatzbiotope.to_linie
ADD COLUMN last_modified timestamp without time zone;

CREATE FUNCTION gl_ersatzbiotope.to_linie_update()
  RETURNS TRIGGER
  LANGUAGE 'plpgsql'
AS $BODY$

BEGIN

NEW.last_modified = localtimestamp(0);
NEW.laenge_m = ST_Length(geo_obj);

RETURN NEW;
END;
$BODY$;

ALTER FUNCTION gl_ersatzbiotope.to_linie_update()
  OWNER TO gl_ersatzbiotope_write;

CREATE TRIGGER to_linie_update
  BEFORE UPDATE
  ON gl_ersatzbiotope.to_linie
  FOR EACH ROW
  EXECUTE FUNCTION gl_ersatzbiotope.to_linie_update();

-- to_punkt
ALTER TABLE gl_ersatzbiotope.to_punkt
ADD COLUMN last_modified timestamp without time zone;

CREATE FUNCTION gl_ersatzbiotope.to_punkt_update()
  RETURNS TRIGGER
  LANGUAGE 'plpgsql'
AS $BODY$

BEGIN

NEW.last_modified = localtimestamp(0);


RETURN NEW;
END;
$BODY$;

ALTER FUNCTION gl_ersatzbiotope.to_punkt_update()
  OWNER TO gl_ersatzbiotope_write;

CREATE TRIGGER to_punkt_update
  BEFORE UPDATE
  ON gl_ersatzbiotope.to_punkt
  FOR EACH ROW
  EXECUTE FUNCTION gl_ersatzbiotope.to_punkt_update();

-- Set up priviledges for schema -----------------------------------------------------
GRANT USAGE ON SCHEMA gl_ersatzbiotope TO gl_ersatzbiotope_read;

GRANT ALL ON ALL TABLES IN SCHEMA gl_ersatzbiotope TO gl_ersatzbiotope_write;
GRANT SELECT ON ALL TABLES IN SCHEMA gl_ersatzbiotope TO gl_ersatzbiotope_read;

-- Column Comments -------------------------------------------------------------------

