-- This setup script was generated by render_sql_template.py in the aue_interlis git repo.
-- 
-- Usage:
-- This script is intended to directly run after importing the corresponding INTERLIS
-- schema and catalogues using ili2pg. It sets up common Postgres-specific functionality 
-- such:
--  - adding last_modified columns and corresponding trigger functionality
--  - setting up priviledges 
--  - adding enum constraints that ili2pg doesn't implement
--  - adding not null constraints (this is a workaround for mandatory catalogue fkey columns
--    not getting materialized with NOT NULL by ili2pg)


-- Drop unused catref tables -----------------------------------------------------------

-- Add NOT NULL constraints ------------------------------------------------------------

-- Configure uuid for t_ili_tid --------------------------------------------------------
ALTER TABLE pub_gl_bohrkataster.grundwasserbohrung
ALTER COLUMN t_ili_tid TYPE uuid USING t_ili_tid::uuid;

ALTER TABLE pub_gl_bohrkataster.grundwasserbohrung
ALTER COLUMN t_ili_tid SET DEFAULT uuid_generate_v4();

-- Create Domains for custom Enum-Types ------------------------------------------------

-- Add Trigger Setup ------------------------------------------------------------

-- Set up priviledges for schema and its tables ---------------------------------------
GRANT USAGE ON SCHEMA pub_gl_bohrkataster TO dbu_aue_gsbohrung_read;

GRANT ALL ON ALL TABLES IN SCHEMA pub_gl_bohrkataster TO dbu_aue_gsbohrung_write;
GRANT SELECT ON ALL TABLES IN SCHEMA pub_gl_bohrkataster TO dbu_aue_gsbohrung_read;

-- Column Comments -------------------------------------------------------------------

