java -jar ili2pg-5.5.1.jar --schemaimport \
  --dbhost srv-gisiap-02.glnet.ch \
  --dbport 5432 \
  --dbdatabase glarus \
  --dbusr gisuploadmanager \
  --dbpwd $DB_PASSWORD \
  --dbschema pub_gl_bohrkataster \
  --defaultSrsAuth EPSG \
  --defaultSrsCode 2056 \
  --createFk \
  --createFkIdx \
  --createGeomIdx \
  --createTidCol \
  --createBasketCol \
  --createNumChecks \
  --createUnique \
  --setupPgExt \
  --strokeArcs \
  --coalesceCatalogueRef \
  --coalesceMultiSurface \
  --coalesceMultiPoint \
  --coalesceMultiLine \
  --smart2Inheritance \
  --createMetaInfo \
  --iliMetaAttrs iliMetaAttrs.toml \
  --preScript gsbohrung/scripts/schemaimport_pub_gl_bohrkataster_pre-script.sql \
  gsbohrung/model/GL_Bohrkataster_Publikation_V1.ili # path to ili model passed as first argument when calling the script
