java -jar ili2pg-5.5.1.jar --schemaimport \
  --dbhost localhost \
  --dbport 5432 \
  --dbdatabase test_db \
  --dbusr postgres \
  --dbpwd postgres \
  --dbschema kbs_v1_5 \
  --defaultSrsAuth EPSG \
  --defaultSrsCode 2056 \
  --createFk \
  --createFkIdx \
  --createGeomIdx \
  --createTidCol \
  --createBasketCol \
  --createNumChecks \
  --createUnique \
  --setupPgExt \
  --strokeArcs \
  --coalesceCatalogueRef \
  --smart2Inheritance \
  --createMetaInfo \
  --iliMetaAttrs iliMetaAttrs.toml \
  ili_models/kbs_V1_5.ili # path to ili model passed as first argument when calling the script
