-- This setup script was generated by render_sql_template.py in the aue_interlis git repo.
-- 
-- Usage:
-- This script is intended to directly run after importing the corresponding INTERLIS
-- schema and catalogues using ili2pg. It sets up common Postgres-specific functionality 
-- such:
--  - adding last_modified columns and corresponding trigger functionality
--  - setting up priviledges 
--  - adding enum constraints that ili2pg doesn't implement
--  - adding not null constraints (this is a workaround for mandatory catalogue fkey columns
--    not getting materialized with NOT NULL by ili2pg)


-- Drop unused catref tables -----------------------------------------------------------
DROP TABLE prod_gl_gewaesserzustand.art_gruppierung_catref;
DROP TABLE prod_gl_gewaesserzustand.erhebung_catref;
DROP TABLE prod_gl_gewaesserzustand.gewaessertyp_catref;
DROP TABLE prod_gl_gewaesserzustand.parameter_catref;
DROP TABLE prod_gl_gewaesserzustand.periodizitaet_catref;
DROP TABLE prod_gl_gewaesserzustand.tel_typ_catref;

-- Add NOT NULL constraints ------------------------------------------------------------
ALTER TABLE prod_gl_gewaesserzustand.messgruppierung
ALTER COLUMN gewaessertyp SET NOT NULL;
ALTER TABLE prod_gl_gewaesserzustand.messgruppierung
ALTER COLUMN art_gruppierung SET NOT NULL;
ALTER TABLE prod_gl_gewaesserzustand.werterhebung
ALTER COLUMN aparameter SET NOT NULL;
ALTER TABLE prod_gl_gewaesserzustand.werterhebung
ALTER COLUMN erhebung SET NOT NULL;


-- Create Domains for custom Enum-Types ------------------------------------------------CREATE DOMAIN prod_gl_gewaesserzustand.messgruppierung_standort_typ_enum as TEXT
CHECK (VALUE IN ('Probeentnahmestandort','Stationsstandort'));

ALTER TABLE prod_gl_gewaesserzustand.messgruppierung
ALTER COLUMN standort_typ TYPE prod_gl_gewaesserzustand.messgruppierung_standort_typ_enum;

-- Add last_modified columns ------------------------------------------------------------

-- messgruppierung
ALTER TABLE prod_gl_gewaesserzustand.messgruppierung
ADD COLUMN last_modified timestamp without time zone;

CREATE FUNCTION prod_gl_gewaesserzustand.messgruppierung_update()
  RETURNS TRIGGER
  LANGUAGE 'plpgsql'
AS $BODY$

BEGIN
NEW.last_modified = localtimestamp(0);
RETURN NEW;
END;
$BODY$;

ALTER FUNCTION prod_gl_gewaesserzustand.messgruppierung_update()
  OWNER TO prod_gl_gewaesserzustand_write;

CREATE TRIGGER messgruppierung_update
  BEFORE UPDATE
  ON prod_gl_gewaesserzustand.messgruppierung
  FOR EACH ROW
  EXECUTE FUNCTION prod_gl_gewaesserzustand.messgruppierung_update();

-- werterhebung
ALTER TABLE prod_gl_gewaesserzustand.werterhebung
ADD COLUMN last_modified timestamp without time zone;

CREATE FUNCTION prod_gl_gewaesserzustand.werterhebung_update()
  RETURNS TRIGGER
  LANGUAGE 'plpgsql'
AS $BODY$

BEGIN
NEW.last_modified = localtimestamp(0);
RETURN NEW;
END;
$BODY$;

ALTER FUNCTION prod_gl_gewaesserzustand.werterhebung_update()
  OWNER TO prod_gl_gewaesserzustand_write;

CREATE TRIGGER werterhebung_update
  BEFORE UPDATE
  ON prod_gl_gewaesserzustand.werterhebung
  FOR EACH ROW
  EXECUTE FUNCTION prod_gl_gewaesserzustand.werterhebung_update();

-- messnetz
ALTER TABLE prod_gl_gewaesserzustand.messnetz
ADD COLUMN last_modified timestamp without time zone;

CREATE FUNCTION prod_gl_gewaesserzustand.messnetz_update()
  RETURNS TRIGGER
  LANGUAGE 'plpgsql'
AS $BODY$

BEGIN
NEW.last_modified = localtimestamp(0);
RETURN NEW;
END;
$BODY$;

ALTER FUNCTION prod_gl_gewaesserzustand.messnetz_update()
  OWNER TO prod_gl_gewaesserzustand_write;

CREATE TRIGGER messnetz_update
  BEFORE UPDATE
  ON prod_gl_gewaesserzustand.messnetz
  FOR EACH ROW
  EXECUTE FUNCTION prod_gl_gewaesserzustand.messnetz_update();

-- verantwortlichkeit
ALTER TABLE prod_gl_gewaesserzustand.verantwortlichkeit
ADD COLUMN last_modified timestamp without time zone;

CREATE FUNCTION prod_gl_gewaesserzustand.verantwortlichkeit_update()
  RETURNS TRIGGER
  LANGUAGE 'plpgsql'
AS $BODY$

BEGIN
NEW.last_modified = localtimestamp(0);
RETURN NEW;
END;
$BODY$;

ALTER FUNCTION prod_gl_gewaesserzustand.verantwortlichkeit_update()
  OWNER TO prod_gl_gewaesserzustand_write;

CREATE TRIGGER verantwortlichkeit_update
  BEFORE UPDATE
  ON prod_gl_gewaesserzustand.verantwortlichkeit
  FOR EACH ROW
  EXECUTE FUNCTION prod_gl_gewaesserzustand.verantwortlichkeit_update();

-- Set up priviledges for schema -----------------------------------------------------
GRANT USAGE ON SCHEMA prod_gl_gewaesserzustand TO _read;

GRANT ALL ON ALL TABLES IN SCHEMA prod_gl_gewaesserzustand TO _write
GRANT SELECT ON ALL TABLES IN SCHEMA prod_gl_gewaesserzustand TO _read

-- Column Comments -------------------------------------------------------------------
COMMENT ON COLUMN prod_gl_gewaesserzustand.messgruppierung.gueltig_bis 
  IS 'In Betrieb: 31.12.2999 (defaultwert), sonst Abschlussdatum';
COMMENT ON COLUMN prod_gl_gewaesserzustand.werterhebung.gueltig_bis 
  IS 'In Betrieb: 31.12.2999 (defaultwert), sonst Abschlussdatum';
COMMENT ON COLUMN prod_gl_gewaesserzustand.messnetz.gueltig_bis 
  IS 'In Betrieb: 31.12.2999 (defaultwert), sonst Abschlussdatum';
COMMENT ON COLUMN prod_gl_gewaesserzustand.werterhebung.vorgaenger 
  IS 'Falls Zeitreihen von nahe gelegenen Stationen zusammengeführt werden, weil sie homogen sind, wird der Code der Station der zugeordneten Zeitreihe angegeben. ';

